--- git/docker/amd64/Dockerfile	2022-12-24 16:59:28.554597529 +0100
+++ Dockerfile	2022-12-24 18:12:24.069923032 +0100
@@ -84,6 +84,26 @@
 # hadolint ignore=DL3059
 RUN cargo build --features ${DB} --release
 
+####################### dpkg target ##########################
+FROM build as dpkg
+RUN mkdir /outdir
+RUN mkdir -p /vaultwarden_package/DEBIAN
+RUN mkdir -p /vaultwarden_package/usr/local/bin
+RUN mkdir -p /vaultwarden_package/usr/lib/systemd/system
+RUN mkdir -p /vaultwarden_package/etc/@@PACKAGEDIR@@
+RUN mkdir -p /vaultwarden_package/usr/share/@@PACKAGEDIR@@
+
+WORKDIR /vaultwarden_package
+COPY debian/control /vaultwarden_package/DEBIAN/control
+COPY debian/postinst /vaultwarden_package/DEBIAN/postinst
+COPY debian/conffiles /vaultwarden_package/DEBIAN/conffiles
+COPY debian/config.env /vaultwarden_package/etc/@@PACKAGEDIR@@
+COPY debian/@@EXECUTABLENAME@@.service /vaultwarden_package/usr/lib/systemd/system
+COPY --from=vault /web-vault /vaultwarden_package/usr/share/@@PACKAGEDIR@@/web-vault
+COPY --from=build app/target/release/vaultwarden /vaultwarden_package/usr/local/bin/@@EXECUTABLENAME@@
+
+RUN dpkg-deb --build . /outdir/@@PACKAGEDIR@@.deb
+
 ######################## RUNTIME IMAGE  ########################
 # Create a new stage with a minimal image
 # because we already have a binary built
