--- git/docker/armv7/Dockerfile	2021-02-12 11:45:13.763372371 +0100
+++ Dockerfile	2021-02-12 12:25:50.078877369 +0100
@@ -157,3 +157,23 @@
 WORKDIR /
 ENTRYPOINT ["/usr/bin/dumb-init", "--"]
 CMD ["/start.sh"]
+
+####################### dpkg target ##########################
+FROM build as dpkg
+RUN mkdir -p /vaultwarden_package/DEBIAN
+RUN mkdir -p /vaultwarden_package/usr/local/bin
+RUN mkdir -p /vaultwarden_package/usr/lib/systemd/system
+RUN mkdir -p /vaultwarden_package/etc/@@PACKAGEDIR@@
+RUN mkdir -p /vaultwarden_package/usr/share/@@PACKAGEDIR@@
+
+WORKDIR /vaultwarden_package
+COPY debian/control /vaultwarden_package/DEBIAN/control
+COPY debian/postinst /vaultwarden_package/DEBIAN/postinst
+COPY debian/conffiles /vaultwarden_package/DEBIAN/conffiles
+COPY Rocket.toml /vaultwarden_package/etc/@@PACKAGEDIR@@
+COPY debian/config.env /vaultwarden_package/etc/@@PACKAGEDIR@@
+COPY debian/@@EXECUTABLENAME@@.service /vaultwarden_package/usr/lib/systemd/system
+COPY --from=vault /web-vault /vaultwarden_package/usr/share/@@PACKAGEDIR@@/web-vault
+COPY --from=build app/target/armv7-unknown-linux-gnueabihf/release/vaultwarden /vaultwarden_package/usr/local/bin/@@EXECUTABLENAME@@
+
+RUN dpkg-deb --build . @@PACKAGEDIR@@.deb
